name: clang-format 格式

on:
  push:
    branches:
      - '*' # all

jobs:
  clang-format:
    runs-on: ubuntu-latest # Ubuntu 

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format # install clang-format

      - name: findfiles
        id: find_files
        run: |
          FILES=$(find . -regex '.*\.\(c\|cc\|cpp\|cxx\|h\|hpp\|hxx\|objc\|objcpp\)$' -print0 | tr '\0' ' ') # 查找常见 C/C++/ObjC 文件
          echo "::set-output name=files::$FILES" # 将找到的文件列表设置为输出

      - name: use format
        run: clang-format -i --style=file ${{ steps.find_files.outputs.files }} # use .clang-format 

      - name: check changes of codes
        id: check_format
        run: |
          git diff --check || echo "::set-output name=has_changes::true" # 检查是否有格式变动，如果有则设置 has_changes 输出为 true

      - name: commit
        if: steps.check_format.outputs.has_changes == 'true'
        run: |
          git config --local user.name "GitHub Action" # 配置提交者用户名
          git config --local user.email "action@github.com" # 配置提交者邮箱
          git commit -am "Fix: Apply clang-format style" # 提交更改，提交信息可以自定义
          git push # 推送提交到仓库